name: Android CI

on:
  workflow_dispatch:    # 添加手动触发入口
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  android:
    runs-on: android

    env:
      CCACHE_DIR: /home/runner/.cache/ccache
      CCACHE_COMPILERCHECK: content
      CCACHE_SLOPPINESS: time_macros
      OS: android
      TARGET: universal

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          fetch-tags: true

      - name: Set tag name
        run: |
          if [[ "$GITHUB_REF_TYPE" == "tag" ]]; then
              echo "GIT_TAG_NAME=$GITHUB_REF_NAME" >> $GITHUB_ENV
          fi
          echo $GIT_TAG_NAME

      - name: Build
        run: ANDROID_HOME=/opt/android-sdk ./.ci/android/build.sh

      - name: Package Android artifacts
        run: ./.ci/android/package.sh

      - name: Upload Android artifacts
        uses: forgejo/upload-artifact@v4
        with:
          name: android.zip
          path: artifacts/*
